version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "3666:3666"
    volumes:
      - ./backend/data:/app/data
    environment:
      - PORT=3666

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3666
    stdin_open: true
    tty: true
